language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: GuGGI2l/mGEyIHEDxPIak2n7l8Wtl6NVo9bEfSLBA0z2zIU3MjgmTEs9Lt36Vv5eR6j01I+XmCs4v53P8SPj9NLW3FjWioo0t+ytJvO0BPP61oc6aZVXV8EAV6Z/YYPY+PdTYH9IuDev8JMr57wrpGNEA7qiUUv7PkyPcDjmO1nMwjK3/JkF3u6HiNqhcr2arEgcic/Hfp0xi2Mmz8QxslnZz3TSPgcmEsLeW4RkmhmoYB6RNfnPT3L1hprkmE4kSGB3ys8e55cMRSxEwGfsYdpCp0MI3NyGNSPARsZDEYTGVwr/SI0NYdOc2KUTo6AKk9HJtGYNPmTapxy16wQ2n6jifMScMBxYIL4OBytdDp5wHBEKhkRDMV8qQQ/gTmbETAfCN3ht2wU64KBZDMZ8dTG6c99qmnVq5jQmb/dJUQxV9RLnwsoKb4W6AejeP9k9RZbYg+necp4aqNI6TFUYWTwgAfMNZbteE6PENmw6k9WJSmWSGnJ/euaxqGHLDvEvDfMFvG3Utkk1kwpdXAlPeIL8yDsd4FA/YjrGAG0ThXJRfNznRsrffPqmfHCifp7bW4r4hUHgU77gsrZ4QBpcz1f3pZG/h3SQKR6a+lESWlk7eV92bTjsbEU8n0pDcqY3t3fWscCtU70nlWLcJgrgmFiH7oGW9GB33jG0Y2sRrY8=
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: ffWZwAYAg6uBLCrNZ4cOZKJWnzHRbcw0FxhGInSoQ0c/t2Dug2lQ7atancyJ4ljzfNv16CGTF3YPdoGxC685JKrMebONNaej0wGkulfsUJ3n91kpYoPt1iUUoQzWGKXAlEKPtsFF960dWDDb2SWvaGSUcQjYj2g8eiGPpcDjAcNNv6s4T+YjNU8jPITICGXTbbC5MlxY0rLkb+pJ/lQRRFXjg3BRwYEKwOM9g/U89QHsdkVVQbshwJg514vqjNt/84P62mxhKvi3HNvvRxeCWqVzVsHXKSl5DxRYpq2Gea1bz6boo9tBI0tLV2UZSQQNWqMdujF19MixIYU+CWg4qyJW84OWQobgANXCHZ3TlbrBrcftg3PjOht1jQuOtLrykyxH6HeefG4x++6B/YiFZ87t6CI002LiMfHI+wH3SLIPZXtlWIwjTa75asEzIh87IPOw4xKoeq1W9AU2EwgaD1+pJHGNubsn8EU/iexbqLFZzLrcIE4opYFKjeCA7Yb5Usqco4c5iX/SitDrxqMVD77iqTVhGkmEGUXUaDReRSkZXZyQIU/Cw8qwi1zppJIqgRa7SMZ4/LNUTMQOeX2oPnjuMzSmQUy/+p1yfbrOADSj5H/Uffy/c5p3XXje0q5RHrJ4p6mukfZJJP/u6Sr6Et4rctsioqEkIDCnXObZTcY=
  app: secomp-base-app