language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: O3aQP+IUAs4h3/PcJvq+FRNqKKI5gkwlzAEPDVkvg50/gaN6ZNpF4C+mO3wGlhGnGZI6gizagNBXaPSPX3He+nBlRWu7fxmmzOAmnnbdw36l2rAZJwcDAgrxxtuNMIhak1PQndW1aO2pRg0otQfBi0rzOcvNuJmPbBxWuFE2rADs3YZ4m9GGDQZG/G1efoQdl9PXD59B4bcgqSk7/KQtpS162dXIIE1WA1zEcJ0CHOcSjU1MFpctSRA5at1NveX8sffn1jjsZDu9Mp0adaEEI6+Hp+GIuuryhmTcgIRaX8zmGiP1anG76OfF2PwFaSWqioxySYL7E5Ki9qSHbQ4GYXLj/fw8LGAThW8NFYFRucjYOPsut2h06IjOFl2tvcGiI19NoJcaqx9Lk0STiSAni2ytDuEMjHJvbVlCeV+RJFTxMk0PltLOg8UM7GeaRNtQyKxmAPzHCI1mlqNnbEf+vb8I7wu+/MclPmlWm3QHhGsWFogGM6HBCeVM0n7bZt+/PQsDgNhOhOJIFr2lwfGFGI4wxJqVzvwheWn9nLcxZWLf/uAYAPY9A4I1vs+ui8EY5tyLWqGCqmXB35AvTZK1xnl0iAPiCQvtRaWhmoy5lC3neNgJ+oQtarZqqsitWA1GoY3LydHXGAQqfKeJbYZ6g4VoIlQ0A8auz8rrX2HO8Yc=
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  api_key:
    secure: LHd/Qvfj47/1UHSQFVQ3YN12RSSPFiOzK3qbH9rAx6nk/Hi+4B2+Bz60C5p3pvKqqVnhQKkDGk4IEenz93T5Qk8buPZ8eBwYSEfhvSGSvtqSFYjAoco8I3z5MxWJrzfVk3/7ufCjpsdx7X6+rarQk0bHjifFyezq+h6qMIEy8hiteYkdyKHfXozIhM68tyt8yUDU+3TNSmYf+Tbqe/j+nY8hjyhKrXEVP/5nEQmoKEqP4jflOTCh/9Wn6e8mk0FknuNgTsJeCMmfPB2YLmCxbQMi6FQtU067clTVX0ApP1FSCQhnWgrjxpqugKGM6o+NCzosRX7cDzWrwY8TOz8G4nahJWux25CEvv5KKT/miRHV5ov/CxgtOfVRkVVQFjOzokXZTOA2A9VgAVS7P530WX2RrynQdeDCuM8j0KrnbiTA1e07h0R1ZTXowewW0BC9vmN1LRVZ6I6CIwXoMXuzhBWPQfGt7cnAFeaumMndm9xGJhlLKSVBTMQpy02pim5xnBPcnj1aoCnA9/aZHwoaho7ZmplP9ZS1byosgsGu6Di84fdQYsNIremdP8t64OmB8cEE4tuM9/IcJi450WERoq2k03o7F4JvUNp7f1jAAhDJAoIoQjJDrHiSGvpDBtzC9mUxdbbz4WK65GnQF7CRFCi/OPfrpMd6KrBIyKF6XYw=
