# According to https://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true
env:
  global:
    # in this case, the key below is the result of an encryption of the env variable SONAR_TOKEN=b96c4252d8c5e65ee93cdd9d7124be3b0f412502
    - secure: "GuGGI2l/mGEyIHEDxPIak2n7l8Wtl6NVo9bEfSLBA0z2zIU3MjgmTEs9Lt36Vv5eR6j01I+XmCs4v53P8SPj9NLW3FjWioo0t+ytJvO0BPP61oc6aZVXV8EAV6Z/YYPY+PdTYH9IuDev8JMr57wrpGNEA7qiUUv7PkyPcDjmO1nMwjK3/JkF3u6HiNqhcr2arEgcic/Hfp0xi2Mmz8QxslnZz3TSPgcmEsLeW4RkmhmoYB6RNfnPT3L1hprkmE4kSGB3ys8e55cMRSxEwGfsYdpCp0MI3NyGNSPARsZDEYTGVwr/SI0NYdOc2KUTo6AKk9HJtGYNPmTapxy16wQ2n6jifMScMBxYIL4OBytdDp5wHBEKhkRDMV8qQQ/gTmbETAfCN3ht2wU64KBZDMZ8dTG6c99qmnVq5jQmb/dJUQxV9RLnwsoKb4W6AejeP9k9RZbYg+necp4aqNI6TFUYWTwgAfMNZbteE6PENmw6k9WJSmWSGnJ/euaxqGHLDvEvDfMFvG3Utkk1kwpdXAlPeIL8yDsd4FA/YjrGAG0ThXJRfNznRsrffPqmfHCifp7bW4r4hUHgU77gsrZ4QBpcz1f3pZG/h3SQKR6a+lESWlk7eV92bTjsbEU8n0pDcqY3t3fWscCtU70nlWLcJgrgmFiH7oGW9GB33jG0Y2sRrY8="
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: LHd/Qvfj47/1UHSQFVQ3YN12RSSPFiOzK3qbH9rAx6nk/Hi+4B2+Bz60C5p3pvKqqVnhQKkDGk4IEenz93T5Qk8buPZ8eBwYSEfhvSGSvtqSFYjAoco8I3z5MxWJrzfVk3/7ufCjpsdx7X6+rarQk0bHjifFyezq+h6qMIEy8hiteYkdyKHfXozIhM68tyt8yUDU+3TNSmYf+Tbqe/j+nY8hjyhKrXEVP/5nEQmoKEqP4jflOTCh/9Wn6e8mk0FknuNgTsJeCMmfPB2YLmCxbQMi6FQtU067clTVX0ApP1FSCQhnWgrjxpqugKGM6o+NCzosRX7cDzWrwY8TOz8G4nahJWux25CEvv5KKT/miRHV5ov/CxgtOfVRkVVQFjOzokXZTOA2A9VgAVS7P530WX2RrynQdeDCuM8j0KrnbiTA1e07h0R1ZTXowewW0BC9vmN1LRVZ6I6CIwXoMXuzhBWPQfGt7cnAFeaumMndm9xGJhlLKSVBTMQpy02pim5xnBPcnj1aoCnA9/aZHwoaho7ZmplP9ZS1byosgsGu6Di84fdQYsNIremdP8t64OmB8cEE4tuM9/IcJi450WERoq2k03o7F4JvUNp7f1jAAhDJAoIoQjJDrHiSGvpDBtzC9mUxdbbz4WK65GnQF7CRFCi/OPfrpMd6KrBIyKF6XYw=
